<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/01_Numpy/numpy_day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
arr * 5  #broadcasting


array([ 5, 10, 15, 20, 25, 30, 35])

In [ ]:
arr[5]

np.int64(6)

In [ ]:
arr[6]

np.int64(7)

In [ ]:
#in array we can print multiple indexes together - FANCY INDEXING
arr[[5,6]]

array([6, 7])

In [ ]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,"chacha"]])
matrix  #if only one element is of string ,complete matrix will be of string

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['9', '10', '11', '12'],
       ['13', '14', '15', 'chacha']], dtype='<U21')

In [ ]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(matrix[2:4, 2:4])

[[11 12]
 [15 16]]


You can do this fancy indexing in 2D Matrix aswell

In [ ]:
matrix = np.arange(1,13).reshape(3,4)
print(matrix)
print(matrix[[0,0],[1,2]])     #[[rows],[columns]]
print(matrix[[1,1],[2,3]])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[2 3]
[7 8]


##Conditional Selection
Find values based on conditions or replace them.

In [ ]:
arr = np.array([10,2,15,16,18,11])
arr[arr > 15]

#Replace the elements where value is greater than 15
#METHOD 1 (AAM ZINDAGI)
arr[arr > 15] = 0
print(arr)

#METHOD 2 (MENTOS ZINDAGI)
np.where(arr > 15, 0, arr)  #(condition, kisse replace?, )

[10  2 15  0  0 11]


array([10,  2, 15,  0,  0, 11])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

##Concatenation & Stacking

In [ ]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,6,7])

print(a)
print(b)

np.concatenate([a,b])

[1 2 3 4]
[5 6 7]


array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
MatrixA = np.array([[1,2,3],[4,5,6]])
MatrixB = np.array([[1,1,1,],[2,2,2]])

print(MatrixA)
print(MatrixB)

np.concatenate([MatrixA, MatrixB])


[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [2 2 2]]


array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

Vertical & Horizontal Stacking

In [ ]:
#Vertical Stacking  (works same as concatenation)

np.vstack([MatrixA, MatrixB])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
#Horizontal Stacking

np.hstack([MatrixA, MatrixB])

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [ ]:
#1. shape
#2. size
#3. descriptive statistical function(mean, std, variance, max, min)

#4.** .skew()
