<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/01_Numpy/numpy_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2],[3,4],[5,6]])
print(f"Array 1 : {arr}")
print(f"Array 2 : {arr2}")

#1. shape -> no. of rows and columns
print(f"The shape of the array is {arr.shape}")
print(f"The shape of the array 2 is {arr2.shape}")


#2. We have to check dimensions of the array
print(f"The dimensions of the array is {arr.ndim}")
print(f"The dimensions of the array 2 is {arr2.ndim}")

#3. We have to check total number of elements present in your array
print(f"The size of the array 1 is {arr.size}")
print(f"The size of the array 2 is {arr2.size}")

#4. To check the data type
print(f"The data type of the array 1 is {arr.dtype}")
print(f"The data type of the array 2 is {arr2.dtype}")

#5. To convert array into float data type
# use   .astype()
print(arr.astype(float))
print(arr2.astype(float))



Array 1 : [1 2 3 4 5]
Array 2 : [[1 2]
 [3 4]
 [5 6]]
The shape of the array is (5,)
The shape of the array 2 is (3, 2)
The dimensions of the array is 1
The dimensions of the array 2 is 2
The size of the array 1 is 5
The size of the array 2 is 6
The data type of the array 1 is int64
The data type of the array 2 is int64
[1. 2. 3. 4. 5.]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
arr[1]

np.int64(2)

In [ ]:
#slicing.  [start(0):stop:step(1)]
print(arr[1:4])

[2 3 4]


Now lets see the 2D indexing aswell

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
#matrix[row_index, col_index]
print(matrix)
print(matrix[2,2])
print(matrix[0,2])
print(matrix[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
3
6


Now we can also do the slicing lets see the **slicing in 1D**

1D slicing was really easy now lets see the **slicing in 2D**

In [ ]:
matrix
#matrix[row_start_index:row_stop_index, column_start_index:column_stop_index])
print(matrix)

matrix[0:2, 0:2]
matrix[1:3 , 1:3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

There is one more thing known as **Boolean indexing**

In [ ]:
arr = np.array([5,10,15,18,20,22])
arr < 18       #Boolean indexing

array([ True,  True,  True, False, False, False])

In [ ]:
arr = np.array([5,10,15,18,20,22])
arr[arr < 18]

array([ 5, 10, 15])

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [ ]:
import numpy as np
arr = np.arange(1,11)
arr.reshape(2,5)   #(rows,columns)
arr.reshape(5,2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])