<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/01_Numpy/numpy_day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [ ]:
import numpy as np
#Some Basic Arithmetic Operations
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(f"Addition of arr1 and arr2 is {arr1 + arr2}")
print(f"Subtraction of arr1 and arr2 is {arr1 - arr2}")
print(f"Multiplication of arr1 and arr2 is {arr1 * arr2}")
print(f"Division of arr1 and arr2 is {arr1 / arr2}")


Addition of arr1 and arr2 is [ 6  8 10 12]
Subtraction of arr1 and arr2 is [-4 -4 -4 -4]
Multiplication of arr1 and arr2 is [ 5 12 21 32]
Division of arr1 and arr2 is [0.2        0.33333333 0.42857143 0.5       ]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
#Array broadcasting   (interview**)
arr1 * 5

array([ 5, 10, 15, 20])

Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,1,1],[2,2,2],[3,3,3]])
A + B

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [ ]:
import numpy as np
arr = np.array([4,8,15,16,23,42])
print(f"Sum of arr is {arr.sum()}")
print(f"Average of arr is {arr.mean()}")
print(f"Max of arr is {arr.max()}")
print(f"Min of arr is {arr.min()}")
print(f"Standard deviation of arr is {arr.std()} ")
print(f"Variation of arr is {arr.var()} ")


Sum of arr is 108
Average of arr is 18.0
Max of arr is 42
Min of arr is 4
Standard deviation of arr is 12.315302134607444 
Variation of arr is 151.66666666666666 


You can also do the axis based operations row-Wise and Colum-wise

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix.sum(axis = 0)    #Axis = 0 operations on columns
matrix.sum(axis = 1)    #Axis = 1 operations on rows

array([ 6, 15, 24])

In [ ]:
#SORTING - On the elements
arr = np.array([5,6,1,2,0])
print(np.sort(arr))

[0 1 2 5 6]


In [ ]:
#Argsort
#if we have to sort index we use agrument sort
print(np.argsort(arr))

[4 2 3 0 1]


In [ ]:
index = np.argsort(arr)
print("Indexs:", index)
print("Elements after sort :", arr[index])

Indexs: [4 2 3 0 1]
Elements after sort : [0 1 2 5 6]
