<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/01_Numpy/numpy_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
l = [1,2,3,4,5]*5    #in list *5 is not possible
print(l)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
import numpy as np

Lets create a matrix using list

In [ ]:
l = [1,2,3,4,5]
arr = np.array(l)
print(arr*5)

[ 5 10 15 20 25]


Now lets see how matlix looks like using numpy arrays

In [ ]:
l = [[1,2,3,4],[5,6,7,8]]
arr = np.array(l)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
arr = np.zeros(4)   #0. - indicates that methods is made using built in function
print(arr)

[0. 0. 0. 0.]


In [ ]:
print(np.zeros([4,4]))  #[no. of rows, no. of columns]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr = np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [ ]:
arr = np.ones([2,2])
print(arr)

[[1. 1.]
 [1. 1.]]


In [ ]:
arr = np.full(5,7)     #for creating custom array we use .full
print(arr)


[7 7 7 7 7]


In [ ]:
arr = np.arange(1,11,2)  #same as range
arr



array([1, 3, 5, 7, 9])

In [ ]:
arr = np.linspace(0,1,5)    #evenly distributed 5 values
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.eye(6)
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
arr = np.random.rand(3,3)    #rand(rows,columns)
arr                          #float

array([[0.19804247, 0.22001983, 0.2890401 ],
       [0.43096408, 0.45673401, 0.11020628],
       [0.25461708, 0.56047569, 0.87876259]])

In [ ]:
arr = np.random.randint(1,10,(3,3))     #(start,stop,(shape))
print(arr)                              #integer

[[3 2 7]
 [5 2 2]
 [1 1 7]]


In [ ]:
arr = np.random.randn(2,4)
print(arr)
#random values that can be negative as well

[[-0.49876286  1.89659195 -1.51779747 -0.60011682]
 [-0.83628806 -0.21734828  0.3873683   2.02376288]]


arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution