<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/01_Numpy/Assignments/sheet4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Final NumPy Assignment (Classes 1–4)

### Instructions
- Solve all questions.
- Write your code in the code cell below each question.
- Do not modify the questions.
- Total Questions: **30**


# Part A – Array Creation

In [ ]:
import numpy as np

### Q1. Create a NumPy array from the list `[5,10,15,20,25]`.

In [ ]:
arr = np.array([5,10,15,20,25])
print(arr)

[ 5 10 15 20 25]


### Q2. Create a **3×4** array of zeros.

In [ ]:
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Q3. Create a **4×4** array of ones.

In [ ]:
arr = np.ones((4,4))
print(arr)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Q4. Create a **5×5 identity matrix** using `np.eye()`.

In [ ]:
arr = np.eye((5))
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Q5. Create an array from **1 to 50** with a step of **5**.

In [ ]:
arr = np.arange(1,51,5)
print(arr)


[ 1  6 11 16 21 26 31 36 41 46]


# Part B – Array Attributes

### Q6. Find the **shape** of the given array.

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Shape of array 1 ia {arr1.shape}")
print(f"Shape of aaray 2 is {arr2.shape}")

Shape of array 1 ia (7,)
Shape of aaray 2 is (3, 3)


### Q7. Find the **number of dimensions (`ndim`)**.

In [ ]:
print(f"Dimension of array 1 ia {arr1.ndim}")
print(f"Dimension of aaray 2 is {arr2.ndim}")


Dimension of array 1 ia 1
Dimension of aaray 2 is 2


### Q8. Find the **total number of elements (`size`)**.

In [ ]:
print(f"Total no. of elements in array 1 is {arr1.size}")
print(f"Total no. of elements in array 2 is {arr2.size}")


Total no. of elements in array 1 is 7
Total no. of elements in array 2 is 9


### Q9. Find the **data type (`dtype`)**.

In [ ]:
print(f"Data type of array 1 is {arr1.dtype}")
print(f"Data type of array 2 is {arr2.dtype}")


Data type of array 1 is int64
Data type of array 2 is int64


### Q10. Convert the array into **float** datatype.

In [ ]:
print(arr1.astype(float))
print(arr2.astype(float))


[1. 2. 3. 4. 5. 6. 7.]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Part C – Indexing & Slicing

### Q11. Print the **first element** of a 1D array.

In [ ]:
arr = np.array([23,45,7,8,6,567,7,8])
print(arr[0])



23


### Q12. Print the **last element** of a 1D array.

In [ ]:
print(arr[7])


8


### Q13. Print the **first row** of a 2D array.

In [ ]:
matrix = np.random.randint(1,21,(3,4))
print(matrix)

print(matrix)

[[ 8  8  2 15]
 [ 4  6 14 16]
 [20  1  9  1]]


### Q14. Print the **last column** of a 2D array.

In [ ]:
print(matrix[0:3,3:4])

[[15]
 [16]
 [ 1]]


### Q15. Print elements from **index 2 to 7**.

In [ ]:
print(arr[2:8])


[  7   8   6 567   7   8]


### Q16. Reverse the array using slicing.

In [ ]:
print(arr)
print(arr[::-1])


[ 23  45   7   8   6 567   7   8]
[  8   7 567   6   8   7  45  23]


# Part D – Reshape & Flatten

### Q17. Convert a 1D array of **12 elements** into a **3×4** matrix.

In [ ]:
matrix = np.arange(1,13).reshape(3,4)
print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Q18. Reshape the above matrix into **2×6**.

In [ ]:
matrix = np.arange(1,13).reshape(2,6)
print(matrix)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Q19. Flatten the matrix using `flatten()`.

In [ ]:
print(matrix.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Q20. Reshape the array into **4×3**.

In [ ]:
matrix = np.arange(1,13).reshape(4,3)
print(matrix)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Part E – Broadcasting & Arithmetic

### Q21. Add **10** to every element of an array.

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr + 10)


[11 12 13 14 15 16 17]


### Q22. Multiply every element by **5**.

In [ ]:
print(arr * 5)


[ 5 10 15 20 25 30 35]


### Q23. Add two arrays element-wise.

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([8,9,10,11,12,13,14])
print(f"Addition of array 1 and array 2 is {arr1 + arr2}")

Addition of array 1 and array 2 is [ 9 11 13 15 17 19 21]


### Q24. Find the square of every element.

In [ ]:
print(arr*arr)

[ 1  4  9 16 25 36 49]


# Part F – Fancy & Boolean Indexing

### Q25. Using fancy indexing, print **20, 40, 80** from a 1D array.

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[[1,3,7]])



[20 40 80]


### Q26. Using fancy indexing, print the **first and third rows** of a 2D array.

In [ ]:
matrix = np.random.randint(1,21,(3,4))
print(matrix)

print(matrix[[0,0,0,0],[0,1,2,3]])

print(matrix[[2,2,2,2],[0,1,2,3]])

[[ 7  8  1  9]
 [16 14 17  3]
 [20 10 11 16]]
[7 8 1 9]
[20 10 11 16]


### Q27. Using boolean indexing, print elements **greater than 20**.

In [ ]:
arr = np.array([23,51,13,40,25,8,9,16])
print(arr[arr > 20])


[23 51 40 25]


### Q28. Using boolean indexing, print only the **even numbers**.

In [ ]:

print(arr[arr%2 == 0])

[40  8 16]


# Part G – Sorting & Concatenation

### Q29. Sort an array using `np.sort()`.

In [ ]:
arr = np.array([23,51,13,40,25,8,9,16])
print(np.sort(arr))


[ 8  9 13 16 23 25 40 51]


### Q30. Find the sorted indices using `np.argsort()`.

In [ ]:
print(np.argsort(arr))


[5 6 2 7 0 4 3 1]


### Q31. Join two arrays using `np.concatenate()`.

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([10,20,30,40,50,60,70])
print(np.concatenate([arr1,arr2]))

[ 1  2  3  4  5  6  7 10 20 30 40 50 60 70]
