<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/01_Numpy/Assignments/sheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# NumPy Assignment — Array Attributes, Indexing & Slicing



# Q1. Array Attributes

## Problem Statement
Create the following NumPy array:


```
`# This is formatted as code`
```


```python
[10, 20, 30, 40, 50]
```

Print:
- Shape
- Number of Dimensions
- Size
- Data Type

## Sample Output
```python
Shape: (5,)
Dimensions: 1
Size: 5
dtype: int64
```


In [ ]:
import numpy as np

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Sixe:", arr.size)
print("Data type:", arr.dtype)





Shape: (5,)
Dimensions: 1
Sixe: 5
Data type: int64



# Q2. Find Array Shape

## Problem Statement
Create the following array:

```python
[[1,2,3],
 [4,5,6]]
```

Print only the shape of the array.

## Sample Output
```python
(2, 3)
```


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)



# Q3. 1D Indexing

## Problem Statement
Create the array:

```python
[5, 10, 15, 20, 25]
```

Print:
- First element
- Last element

## Sample Output
```python
5
25
```


In [ ]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[0])
print(arr[4])

5
25



# Q4. 2D Indexing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the element `50`.

## Sample Output
```python
50
```


In [ ]:
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix[1,1])



50



# Q5. 2D Indexing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the element `9`.

## Sample Output
```python
9
```


In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[2,2])


9



# Q6. 1D Slicing

## Problem Statement
Create the array:

```python
[10,20,30,40,50,60]
```

Print elements from index 1 to 4.

## Sample Output
```python
[20 30 40 50]
```


In [ ]:
arr = np.array([10,20,30,40,50,60])
print(arr[1:5:1])

[20 30 40 50]



# Q7. 1D Slicing

## Problem Statement
Create the array:

```python
[1,2,3,4,5,6,7,8]
```

Print the first 5 elements.

## Sample Output
```python
[1 2 3 4 5]
```


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0:6])

[1 2 3 4 5 6]



# Q8. 2D Slicing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the first two rows.

## Sample Output
```python
[[1 2 3]
 [4 5 6]]
```


In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:2, 0:3])

[[1 2 3]
 [4 5 6]]



# Q9. 2D Slicing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the first two columns of all rows.

## Sample Output
```python
[[10 20]
 [40 50]
 [70 80]]
```


In [ ]:
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix[0:3, 0:2])

[[10 20]
 [40 50]
 [70 80]]


# Q10. `np.eye()`

## Problem Statement
Using NumPy, create a **4 × 4 identity matrix** using the `np.eye()` function.

Print the resulting matrix.

## Sample Output
```python
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
```

In [ ]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Boolean Indexing (Practice)

**Q1.** Create a NumPy array from 1 to 20. Print only the elements greater than 10 using boolean indexing.



In [ ]:
arr = np.arange(1,21)
print(arr)
arr[arr > 10]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])


**Q2.** Create the array:
```python
arr = np.array([12, 5, 18, 7, 25, 30, 2, 15])
```
Print only the even numbers using boolean indexing.


In [ ]:
arr = np.array([12, 5, 18, 7, 25, 30, 2, 15])
print(arr[arr % 2 == 0])

[12 18 30  2]



**Q3.** Create a 4×4 random integer array (1–50). Print only the values greater than 25 using boolean indexing.


In [ ]:
arr = np.random.randint(1,51,(4,4))
print(arr)
print(arr[arr > 25])

[[ 4  6 28  2]
 [19 49 49 13]
 [39 22  1 45]
 [27 46 29 49]]
[28 49 49 39 45 27 46 29 49]
