<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/01_Numpy/Assignments/sheet3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Assignment – Class 4

**Topics:** Fancy Indexing, Conditional Selection, `np.sort()`, `np.argsort()`, `np.concatenate()`

Solve each question in the code cell below it.

In [ ]:
import numpy as np


## Q1. Create `arr = np.array([10,20,30,40,50,60,70,80])`. Print **20, 50, 80** using fancy indexing.

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80])
arr[[1,4,7]]


array([20, 50, 80])

## Q2. Using the same array, print **10, 30, 70** and then **40, 60** using fancy indexing.

In [ ]:
print(arr[[0,2,6]])
print(arr[[3,5]])

[10 30 70]
[40 60]


## Q3. Create a **3×3** matrix. Print the **first row** and **third row** using fancy indexing.

In [ ]:
matrix = np.arange(1,10).reshape(3,3)
print(matrix)
print(matrix[[0]])
print(matrix[[2]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[[7 8 9]]


## Q4. Using the same matrix, print the **first column** and **last column** using fancy indexing.

In [ ]:

print(matrix[[0,1,2],[0,0,0]])
print(matrix[[0,1,2],[2,2,2]])

[1 4 7]
[3 6 9]


## Q5. Create `arr = np.array([5,12,18,7,20,25,30,2])`. Print only elements **greater than 15**.

In [ ]:
arr = np.array([5,12,18,7,20,25,30,2])
arr[arr > 15]


array([18, 20, 25, 30])

## Q6. Using the same array, print only the **even numbers**.

In [ ]:
print(arr[arr%2 == 0])


[12 18 20 30  2]


## Q7. Using the same array, print only the numbers **less than 20**.

In [ ]:
print(arr[arr<20])


[ 5 12 18  7  2]


## Q8. Create `arr = np.array([18,5,27,10,3,15])`. Sort the array using `np.sort()`.

In [ ]:
arr = np.array([18,5,27,10,3,15])
print(np.sort(arr))


[ 3  5 10 15 18 27]


## Q9. Using the same array, find the indices that would sort the array using `np.argsort()`.

In [ ]:
print(np.argsort(arr))


[4 1 3 5 0 2]


## Q10. Create `arr1 = np.array([1,2,3])` and `arr2 = np.array([4,5,6])`. Join both arrays using `np.concatenate()`.

In [ ]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
np.concatenate((arr1,arr2))



array([1, 2, 3, 4, 5, 6])