<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/01_Numpy/Assignments/sheet2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📝 NumPy Assignment – Class 3

### Instructions
- Import NumPy as `np`.
- Solve each question in the code cell below it.
- Print the output wherever required.

## Q1. Import NumPy as `np`.

In [ ]:
import numpy as np

## Q2. Create a NumPy array: `[10, 20, 30, 40, 50]`.

In [ ]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

## Q3. Add `5` to every element of the above array.

In [ ]:
print(arr+5)

[15 25 35 45 55]


## Q4. Multiply every element by `2`.

In [ ]:
print(arr*2)

[ 20  40  60  80 100]


## Q5. Create the following 3×3 array:
```
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(matrix)


[[1 2 3]
 [4 5 6]
 [6 7 8]]


## Q6. Add `10` to every element of the above array.

In [ ]:
print(matrix + 10)

[[11 12 13]
 [14 15 16]
 [16 17 18]]


## Q7. Multiply every element of the above array by `3`.

In [ ]:
print(matrix*3)

[[ 3  6  9]
 [12 15 18]
 [18 21 24]]


## Q8. Create `arr = np.array([1,2,3])` and add it to:
```
[[10,20,30],
 [40,50,60]]
```

In [ ]:
arr1 = np.array([1,2,3])
arr*10
arr2 = np.array([40,50,60])
arr*10 + arr2


array([50, 70, 90])

## Q9. Create `arr = np.array([5,10,15,20,25])` and find its **sum**.

In [ ]:
arr = np.array([5,10,15,20,25])
print(f"Sum of arr is {arr.sum()} ")

Sum of arr is 75 


## Q10. Find the **mean** of the above array.

In [ ]:
print(f"Mean of arr is {arr.mean()} ")

Mean of arr is 15.0 


## Q11. Find the **maximum** and **minimum** value.

In [ ]:
print(f"Max of arr is {arr.max()} ")

Max of arr is 25 


## Q12. Find the **standard deviation**.

In [ ]:
print(f"Standard deviation of arr is {arr.std()} ")

Standard deviation of arr is 7.0710678118654755 


## Q13. Create:
```
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
```

In [ ]:
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


## Q14. Find the **row-wise sum** (`axis=1`).

In [ ]:
matrix.sum(axis = 1)

array([ 60, 150, 240])

## Q15. Find the **column-wise sum** (`axis=0`).

In [ ]:
matrix.sum(axis = 0)

array([120, 150, 180])